title: Dr. Rajni Toppo
logo: /media/pfp_github.jpeg
description: Healthcare Business Strategist | Consultant | Molecular Pathologist | Health Admin | Medical director| Data Analyst | Clinician | Certified Internal Auditor | QAI Assessor | Driving Innovation & Excellence in Healthcare.
theme: jekyll-theme-minimal
