title: Dr. Rajni Toppo
logo: "https://media.licdn.com/dms/image/v2/D4D35AQF5osiwXNNlCA/profile-framedphoto-shrink_400_400/B4DZWgSLhLHAAc-/0/1742150875497?e=1748638800&v=beta&t=zXvOEky8YbQ1Hjs9XcKXEVn35akbQWlq7O2gYkdrQOk"
theme: jekyll-theme-minimal
